### ISSUE TITLE
Where to store token in mkdocs.yml?

### ISSUE THREAD

**Issue by Guts** [ojacques/mkdocs-git-committers-plugin-2#22]
HI

I'm trying to use your plugin which seems interesting but I can't get a list of authors. Reading your README, I see:

> If the token is not set in mkdocs.yml it will be read from the MKDOCS_GIT_COMMITTERS_APIKEY environment variable.

Where have I to store the token in `mkdocs.yml`?

Do you have a demo website to see how it's rendered?

**Comment by ojacques** [comment]
@Guts - good catch. This was a left over in the documentation: the plugin does not need a GitHub API token anymore.

Regarding a demo site, my [own site](https://ojacques.github.io/blog/2021-03-31/march-2021/) has the plugin enabled (scroll down). I moved to `mkdocs-material-insiders` by @squidfunk which supports the plugin out of the box.

**Comment by Guts** [comment]
Ok, thanks. So I've got another (real) issue.

> I moved to mkdocs-material-insiders by @squidfunk which supports the plugin out of the box.

Only in Insiders version no? I'm sponsoring it too but just to confirm.


off-topic: nice blog. You might be interested in this plugin also: https://blueswen.github.io/mkdocs-glightbox/

**Comment by Guts** [comment]
> Regarding a demo site, my [own site](https://ojacques.github.io/blog/2021-03-31/march-2021/) has the plugin enabled (scroll down).

Would you consider to publish a doc/demo website? IMHO it's always nice to have a real example, some snippets, etc.

**Comment by ojacques** [comment]
Solved, doc issue.
