### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by Kludex** [ojacques/mkdocs-git-committers-plugin-2#24]
After the removal of GH_TOKEN on 1.0.0, we can't retrieve the data from private repositories anymore.

Is there a solution for it besides pinning 0.4.4?

**Comment by ojacques** [comment]
Good point. I tried to add authentication with a token to fetch the `contributors-list` endpoint, but with no success so far.
https://github.com/ojacques/mkdocs-git-committers-plugin-2/tree/private-repos

This is not an API endpoint by itself, so I am not sure this is even possible to do it this way. Suggestions welcomed!

**Comment by Kludex** [comment]
It's not possible :cry: 

> This repository insights graph is available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see "[About repository graphs](https://docs.github.com/en/articles/about-repository-graphs)" and "[GitHub's products](https://docs.github.com/en/articles/github-s-products)."

Reference: https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors

**Comment by ojacques** [comment]
Until 0.4.4, I was using the local git log history, attempting to map it to GitHub users by querying by email - if available. This was unreliable.
With 1.x, I switched to just get a page from GitHub, which is reliable and fast but prevents querying private repos.

I should be able to move to yet another method, leveraging graphql and the commit object. This example below lists the contributors for a given file, not for all of the repository (which we don't need here).

```graphql
{
  repository(owner: "squidfunk", name: "mkdocs-material") {
    object(expression: "master") {
      ... on Commit {
        history(first: 100, path: "docs/getting-started.md") {
          nodes {
            author {
              name,
              email,
              user {
                url
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by adamcrosby** [comment]
We use private repos and private gh_pages for internal knowledge management, project management, etc.
