### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by pawamoy** [ojacques/mkdocs-git-committers-plugin-2#27]
I have a file that is auto-generated, to setup a redirection, and mkdocs-git-committers errors with the following message, preventing me from building my docs in strict mode:

```
ERROR    -  git-committers: HTTP error occurred: 404 Client Error: Not Found for url: https://github.com/mkdocstrings/griffe/contributors-list/master/docs/usage.md
            (404 is normal if file is not on GitHub yet or Git submodule)
```

I'd like to ignore/exclude that file.

For example [mkdocs-git-revision-date-localized-plugin)](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin) has an `exclude` option.

**Comment by ojacques** [comment]
Bonjour Timothée. Thanks for the suggestion, it makes sense. I'll look at it as soon as I can.

**Comment by pawamoy** [comment]
Super, merci Olivier :wink:
