### ISSUE TITLE
Add authentication support for GitHub without read-only view

### ISSUE THREAD

**Issue by milkotodorov** [ojacques/mkdocs-git-committers-plugin-2#30]
For GitHub which has no view only mode an authentication is needed.
Would you consider adding this?

**Comment by ojacques** [comment]
For sure, that is an option - adding authentication.

**Comment by milkotodorov** [comment]
That would be great!
Authentication with user/pass and possibly with token too.

**Comment by ojacques** [comment]
Fixed with #39. Please upgrade to >2.0
