### ISSUE TITLE
Missing dependency: `lxml`

### ISSUE THREAD

**Issue by squidfunk** [ojacques/mkdocs-git-committers-plugin-2#32]
We just [removed `lxml` from our `requirements.txt`](https://github.com/squidfunk/mkdocs-material/commit/0d3cd8a43348ad73b66a3efdbe298ca319f4178d), because we could refactor all uses to the native HTML parser, which makes download and installation of Material for MkDocs much faster. However, now [our builds started failing](https://github.com/squidfunk/mkdocs-material/actions/runs/6037208485/job/16381024143#step:9:63) because this plugin uses BeautifulSoup, which [relies on the presence of a parser library](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser).

Possible solution: adding lxml to the list of dependencies.

**Comment by ojacques** [comment]
Thanks @squidfunk - indeed, I will be looking at removing / simplifying dependencies. There is nothing that simple request could not handle.
