### ISSUE TITLE
Would github actions GITHUB_TOKEN secret be sufficient for use as token in this plugin?

### ISSUE THREAD

**Issue by Andre601** [ojacques/mkdocs-git-committers-plugin-2#42]
Docs say the token in question does not need any scopes. So I was wondering if the `secrets.GITHUB_TOKEN` can be used here when the docs are build using GitHub Actions.
From what I gathered would it be a token like a PAT (I assume) since it accesses and uses the github-actions bot account. And bot accounts can have tokens...

**Comment by ojacques** [comment]
I did not tried myself, but this is an idea worth trying. Note that the token is needed to either bump GitHub API rate limit, or access private repositories. If you have 
- Small documentations (not many pages), 
- In a public repo
- and don't run the build several times within an hour
Then you should not need a token.

Let us know how it goes if you try!

**Comment by Andre601** [comment]
It does work fine from what I can see.

**Comment by RonaldLN** [comment]
@Andre601 could u tell me how to set correctly in workflow to use GITHUB_TOKEN to access private repo?

I set like this

```yaml
name: Deploy MkDocs Site To Public Repo
on:
  push:
    branches: [ "main" ] 

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Site
        run: python3 -m mkdocs build
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        ...
```

but in action I got

```
Run python3 -m mkdocs build
  python3 -m mkdocs build
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib
    MKDOCS_GIT_COMMITTERS_APIKEY: ***
  
INFO    -  "highlightjs" feature is disabled in your plugin configuration.
INFO    -  "mermaid2" feature is disabled in your plugin configuration.
INFO    -  git-committers plugin ENABLED
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/vision-docs/vision-docs/site
INFO    -  Need to generate KDF key...
INFO    -  Need to generate KDF key...
INFO    -  Need to generate KDF key...
INFO    -  Need to generate KDF key...
INFO    -  git-committers: fetching contributors for docs/index.md
ERROR   -  git-committers: error fetching contributors for docs/index.md
ERROR   -  git-committers:   404 Not Found
INFO    -  git-committers: fetching contributors for docs/about.md
ERROR   -  git-committers: error fetching contributors for docs/about.md
ERROR   -  git-committers:   404 Not Found
INFO    -  git-committers: fetching contributors for docs/code-conventions.md
ERROR   -  git-committers: error fetching contributors for docs/code-conventions.md
ERROR   -  git-committers:   404 Not Found
INFO    -  git-committers: fetching contributors for docs/comments.md
...
```

I don't know how to fix it. I tried adjust several times, but never success.

**Comment by RonaldLN** [comment]
@Andre601 Sorry to bother you, I seem to have just found out the reason... This repo is a private repo in a organization, and `Contributors` function is not available for free github organization private repo. So dramatically....😂

**Comment by RonaldLN** [comment]
> [@Andre601](https://github.com/Andre601) could u tell me how to set correctly in workflow to use GITHUB_TOKEN to access private repo? 🙏Thank you in advance!
> 
> I set like this
> 
> name: Deploy MkDocs Site To Public Repo
> on:
>   push:
>     branches: [ "main" ] 
> 
> permissions:
>   contents: read
> 
> jobs:
>   build-and-deploy:
>     runs-on: ubuntu-latest  
> 
>     steps:
>       - name: Checkout Main
>         uses: actions/checkout@v4
>         with:
>           fetch-depth: 0
>           submodules: true 
> 
>       - name: Setup Python
>         uses: actions/setup-python@v5
>         with:
>           python-version: "3.12"
> 
>       - name: Install Dependencies
>         run: pip install -r requirements.txt
> 
>       - name: Build Site
>         run: python3 -m mkdocs build
>         env:
>           MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
> 
>       - name: Deploy
>         ...
> but in action I got
> 
> ```
> Run python3 -m mkdocs build
>   python3 -m mkdocs build
>   shell: /usr/bin/bash -e {0}
>   env:
>     pythonLocation: /opt/hostedtoolcache/Python/3.12.9/x64
>     PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib/pkgconfig
>     Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
>     Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
>     Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
>     LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib
>     MKDOCS_GIT_COMMITTERS_APIKEY: ***
>   
> INFO    -  "highlightjs" feature is disabled in your plugin configuration.
> INFO    -  "mermaid2" feature is disabled in your plugin configuration.
> INFO    -  git-committers plugin ENABLED
> INFO    -  Cleaning site directory
> INFO    -  Building documentation to directory: /home/runner/work/vision-docs/vision-docs/site
> INFO    -  Need to generate KDF key...
> INFO    -  Need to generate KDF key...
> INFO    -  Need to generate KDF key...
> INFO    -  Need to generate KDF key...
> INFO    -  git-committers: fetching contributors for docs/index.md
> ERROR   -  git-committers: error fetching contributors for docs/index.md
> ERROR   -  git-committers:   404 Not Found
> INFO    -  git-committers: fetching contributors for docs/about.md
> ERROR   -  git-committers: error fetching contributors for docs/about.md
> ERROR   -  git-committers:   404 Not Found
> INFO    -  git-committers: fetching contributors for docs/code-conventions.md
> ERROR   -  git-committers: error fetching contributors for docs/code-conventions.md
> ERROR   -  git-committers:   404 Not Found
> INFO    -  git-committers: fetching contributors for docs/comments.md
> ...
> ```
> 
> I don't know how to fix it. I tried adjust several times, but never success.

finally find the reason is, the `branch` is defaultly set to `master`, while branch in my repo should be `main`.....
