### ISSUE TITLE
[Question] How to safely store my token 

### ISSUE THREAD

**Issue by MetalKnight56** [ojacques/mkdocs-git-committers-plugin-2#46]
Ok so i've been having some issues with the git commiters plugin 2, since my documentation has a bunch of pages, and its also deemed to expand in the future... I keep getting error like these:

ERROR - git-committers: error fetching contributors for docs/index.en.md 
ERROR - git-committers: 403 rate limit exceeded - You may have exceeded the API rate limit or need to be need to be authorized. You can set a token under 'token' mkdocs.yml config or MKDOCS_GIT_COMMITTERS_APIKEY environment variable.

So i concluded i had to specify the ``token``, but i was kind of skeptical on how it would be displayed you know? Worried someone could use it to have special privilleges over my other projects as well... So i come here to ask how can i safely store it, obfuscate it somehow, or how can i make usage of the same system @ojacques used for his website - https://ojacques.github.io/ (i do know he`s an insider, but wanted to know if that was exclusive to inders for now too...)

P.S i know it doesn`t need any scopes... (Lmk if i should just uncheck everything like its said on the README, and if i should use Token Classic or whatever the new beta token system is called...)

![image](https://github.com/ojacques/mkdocs-git-committers-plugin-2/assets/77132244/34f6aac0-9b61-4f99-904b-32ca836fdb3c)

Here`s the link to my docs - https://github.com/MetalKnight56/EpicFight-Docs

**Comment by MetalKnight56** [comment]
Found out that environmental variables are a thing lol

**Comment by ojacques** [comment]
Thanks for the report, and well done on finding out the answer by yourself! Indeed, in GitHub and GitLab, you can create secrets, which are not stored in the code, nor will show in the build logs, Enjoy 🥳
