### ISSUE TITLE
Image quality is bad (too small)

### ISSUE THREAD

**Issue by squidfunk** [ojacques/mkdocs-git-committers-plugin-2#9]
Thanks for maintaining this fork! As you may have noticed, insiders-4.19.0 adds [native support](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors) for this nice little plugin. However, I've noticed, that images are rendered too small, due to this line:

https://github.com/ojacques/mkdocs-git-committers-plugin-2/blob/af146bb18bb6297b8b0c0a105a7acf876163ba15/mkdocs_git_committers_plugin_2/plugin.py#L70

Could we remove the `size` parameter? IMHO, it's better left to the template/theme author which size is needed to display the avatar, because the size of the image heavily depends on CSS. For example, [we need `size=72`](https://github.com/squidfunk/mkdocs-material-insiders/blob/707f6922062b0dcd07587ff21ad8d485e45d3c03/src/partials/source-file.html#L98).

**Comment by ojacques** [comment]
Agreed that 24 can be small. Makes sense to remove the size in the avatar attribute.

**Comment by ojacques** [comment]
Fix coming in 0.4.2. @squidfunk - you will have to update mkdocs-material to use `&size=72` instead of `?size=72`.
Nice workaround that you used though!

**Comment by ojacques** [comment]
[0.4.2](https://github.com/ojacques/mkdocs-git-committers-plugin-2/releases/tag/0.4.2) [released](https://pypi.org/project/mkdocs-git-committers-plugin-2/0.4.2/).
